homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('getdata/', views.get_data),
    path('download/', views.download_file)


]

youtube_scrapper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage'))
]

homepage/models.py
from email.policy import default
from django.db import models

# Create your models here.
class YoutubeAPI(models.Model):
    title = models.CharField(max_length=250)
    api_key = models.CharField(max_length=250)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    isnable = models.BooleanField(default=True)
    note = models.TextField(blank=True)

    def __str__(self):
        return self.title

homepage/forms.py
from django import forms

class ChannelIDForm(forms.Form):
    channel_id = forms.CharField(label='channel_id', max_length=250)
    # channel_name = forms.CharField(max_length=250, )
    widget ={
        'channel_id': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Type your YouTube channel ID'})
    }
    

homepage/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from .models import YoutubeAPI
import json
import requests
from tqdm import tqdm
import asyncio, sys
from subprocess import run, PIPE


import  mimetypes, os


# Create your views here.
def homepage(request):
    return render(request, 'homepage/homepage.html')
       

def get_data(request):
    data = YoutubeAPI.objects.all()
    data = data.values()
    youtube_api = data[0]['api_key'] 
    channel_name = request.POST.get('channel_name')
    request.session['channel_name'] = channel_name
    out = run([sys.executable, 'G:\\___epikla\\youtube-scrapper-project\\yt_stats2.py', youtube_api, channel_name], shell=False, stdout=PIPE)
    output = "Completed Process. Your file is: " + channel_name +'.csv'
    request.session['channel_name'] = channel_name
    return render(request, 'homepage/data.html', {'data': output})


def download_file(request):
    data = request.session['channel_name']
    filename = data + '.csv'
    if filename != '':
        BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        filepath = BASE_DIR + '/' + filename
        path = open(filepath, 'rb')
        mime_type, _ = mimetypes.guess_type(filepath)
        response = HttpResponse(path, content_type=mime_type)
        response['Content-Disposition'] = "attachment; filename=%s" % filename
        return response
    else:
        return render(request, 'homepage/homepage.html')
            
    

homepage/templates/homepage/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
   <!-- Mirrored from mironmahmud.com/greeny/assets/ltr/register.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 11 May 2022 09:50:11 GMT -->
   <!-- Added by HTTrack -->
   <meta http-equiv="content-type" content="text/html;charset=utf-8" />
   <!-- /Added by HTTrack -->
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="template" content="YouTube Scrapper">
      <meta name="title" content="YouTube Scrapper">
      <meta name="keywords" content="YouTube Scrapper">
      <title>YouTube Scrapper</title>
      <link rel="icon" href="images/favicon.png">
      <link rel="stylesheet" href="{% static "fonts/flaticon/flaticon.css" %}">
      <link rel="stylesheet" href="{% static "fonts/icofont/icofont.min.css" %}" >
      <link rel="stylesheet" href="{% static "fonts/fontawesome/fontawesome.min.css" %}">
      <link rel="stylesheet" href="{% static "vendor/venobox/venobox.min.css" %}">
      <link rel="stylesheet" href="{% static "vendor/slickslider/slick.min.css" %}">
      <link rel="stylesheet" href="{% static "vendor/niceselect/nice-select.min.css" %}">
      <link rel="stylesheet" href="{% static "vendor/bootstrap/bootstrap.min.css" %}" >
      <link rel="stylesheet" href="{% static "css/main.css" %}">
      <link rel="stylesheet" href="{% static "css/user-auth.css" %}">
   </head>
   <body>
      <section class="user-form-part">
         <div class="container">
            <div class="row justify-content-center">
               <div class="col-12 col-sm-10 col-md-12 col-lg-12 col-xl-10">
                  <!-- <div class="user-form-logo"><a href="index.html"><img src="images/logo.png" alt="logo"></a></div> -->
                  <div class="user-form-card">
                     <div class="user-form-title">
                        <a href={% url "homepage:homepage" %}><h2>Youtube Scrapper</h2></a>
                        <p>Enter YouTube Channel ID and Get Data</p>
                     </div>
                     {% block content %}

                     {% endblock %}  
                  </div>
                  
               </div>
            </div>
         </div>
      </section>
      <script src="{% static "vendor/bootstrap/jquery-1.12.4.min.js" %}"></script>
      <script src="{% static "vendor/bootstrap/popper.min.js" %}"></script>
      <script src="{% static "vendor/bootstrap/bootstrap.min.js" %}"></script>
      <script src="{% static "vendor/countdown/countdown.min.js" %}"></script>
      <script src="{% static "vendor/niceselect/nice-select.min.js" %}"></script>
      <script src="{% static "vendor/slickslider/slick.min.js" %}"></script>
      <script src="{% static "vendor/venobox/venobox.min.js" %}"></script>
      <script src="{% static "js/nice-select.js" %}"></script>
      <script src="{% static "js/countdown.js" %}"></script>
      <script src="{% static "js/accordion.js" %}"></script>
      <script src="{% static "js/venobox.js" %}"></script>
      <script src="{% static "js/slick.js" %}"></script>
      <script src="{% static "js/main.js" %}"></script>
   </body>
   
</html>

homepage/templates/homepage/data.html
{% extends "homepage/base.html" %}
{% block content %}
<div class="user-form-group">
   <form action="/download/" class="user-form" method="POST">
      {% csrf_token %}
      <br>{{data}}<br>
      <div class="form-button"><button type="submit">Download</button></div>
    </form>
       
</div>

{% endblock %}

homepage/templates/homepage/homepage.html
{% extends "homepage/base.html" %}
{% block content %}
<div class="user-form-group">
   <form action="/getdata/" class="user-form" method="post">
      {% csrf_token %}
      <!-- <div class="form-group"><input type="text" id="channel_id" name="channel_id" class="form-control" placeholder="Type your YouTube channel ID"></div> -->
      <div class="form-group"><input type="text" id="channel_name" name="channel_name" class="form-control" placeholder="Type your YouTube channel name"></div>
      <div class="form-button"><button type="submit">Submit</button></div>
      <!-- <br>{{data}}<br> -->
   </form>
 
</div>

{% endblock %}